-- ===================================================================
-- ONEC Pharma - Seed Data (H2 Compatible)
-- ===================================================================

-- Admin User (password: admin123)
MERGE INTO users (id, first_name, last_name, email, password, phone, role, enabled, created_at, updated_at)
KEY (id)
VALUES (1, 'Admin', 'ONEC', 'admin@onecpharma.com', '$2a$10$xP0344TMc8h/Xav3EVNlserSboJNvRg3ASF3erzWw56uVwjSjHBMK', '9999999999', 'ADMIN', true, NOW(), NOW());

-- Categories
MERGE INTO categories (id, name, description, icon, active, display_order, form_schema, target_audience, requires_prescription, health_tags)
KEY (id) VALUES
(1, 'Baby Care', 'Products for newborn and baby care', '👶', true, 1, '{"fields": [{"name": "babyAge", "label": "Baby Age (Months)", "type": "number", "required": true}, {"name": "diaperSize", "label": "Preferred Diaper Size", "type": "select", "options": ["XS", "S", "M", "L", "XL"]}]}', 'BABY', false, 'baby,diapers,baby-powder,infant'),
(2, 'Adult Care', 'Health and hygiene products for adults', '🧑', true, 2, '{"fields": [{"name": "gender", "label": "Gender", "type": "select", "options": ["Male", "Female", "Other"]}]}', 'ALL', false, 'adult,hygiene,protection'),
(3, 'Elderly Care', 'Senior care products, aids and supports', '👴', true, 3, '{"fields": [{"name": "condition", "label": "Primary Condition", "type": "select", "options": ["Arthritis", "Diabetes", "Mobility Issues", "Hypertension", "None"]}, {"name": "mobilityAidRequired", "label": "Requires Mobility Aid?", "type": "boolean"}]}', 'ELDERLY', false, 'elderly,senior,wheelchair,walker,adult-diaper'),
(4, 'Womens Care', 'Female hygiene and wellness products', '👩', true, 4, '{"fields": [{"name": "productType", "label": "Product Type", "type": "select", "options": ["Sanitary Pads", "Menstrual Cups", "Intimate Wash", "Vitamins"]}]}', 'WOMEN', false, 'women,menstruation,pads,intimate-care'),
(5, 'Mens Grooming', 'Mens shaving and grooming essentials', '🧔', true, 5, '{"fields": [{"name": "skinType", "label": "Skin Type", "type": "select", "options": ["Oily", "Dry", "Sensitive", "Normal"]}]}', 'MEN', false, 'shaving,beard,hair-gel,grooming'),
(6, 'Skin Care', 'Dermatological and cosmetic skin products', '✨', true, 6, '{"fields": [{"name": "skinConcerns", "label": "Skin Concern", "type": "select", "options": ["Acne", "Dryness", "Aging", "Pigmentation"]}]}', 'ALL', false, 'skin,sunscreen,moisturizer,acne'),
(7, 'Hair Care', 'Shampoos, conditioners and oils', '💇', true, 7, '{"fields": [{"name": "hairType", "label": "Hair Type", "type": "select", "options": ["Dry", "Oily", "Frizzy", "Dandruff-prone"]}]}', 'ALL', false, 'hair,shampoo,oil,dandruff'),
(8, 'Diabetes Care', 'Glucose monitors, test strips, sugar-free nutrition', '🩸', true, 8, '{"fields": [{"name": "diabetesType", "label": "Diabetes Type", "type": "select", "options": ["Type 1", "Type 2", "Pre-diabetic"]}]}', 'ALL', false, 'diabetes,glucometer,insulin,blood-sugar'),
(9, 'Cardiac Care', 'Blood pressure monitors and cardiac health supplements', '❤️', true, 9, '{"fields": [{"name": "hasBpMonitor", "label": "Do you own a BP Monitor?", "type": "boolean"}]}', 'ALL', false, 'cardiac,heart,bp-monitor,cholesterol'),
(10, 'Orthopedic Care', 'Joint pain relievers, knee braces, supports', '🦴', true, 10, '{"fields": [{"name": "supportArea", "label": "Support Area", "type": "select", "options": ["Knee", "Back", "Wrist", "Ankle", "Neck"]}]}', 'HANDICAPPED', false, 'ortho,joint-pain,brace,support,sprays'),
(11, 'Immunity Boosters', 'Vitamins, supplements and herbal health drinks', '🛡️', true, 11, '{"fields": [{"name": "preferredForm", "label": "Preferred Form", "type": "select", "options": ["Tablet", "Capsule", "Powder", "Liquid"]}]}', 'ALL', false, 'immunity,vitamin-c,zinc,chyawanprash'),
(12, 'Ayurvedic Products', 'Traditional herbal medicines and formulations', '🪷', true, 12, '{"fields": [{"name": "doshaType", "label": "Ayurvedic Dosha (if known)", "type": "select", "options": ["Vata", "Pitta", "Kapha", "Unknown"]}]}', 'ALL', false, 'ayurveda,herbal,ashwagandha,giloy'),
(13, 'Personal Hygiene', 'Soaps, hand washes, sanitizers and oral care', '🧼', true, 13, '{"fields": [{"name": "hygieneType", "label": "Hygiene Category", "type": "select", "options": ["Oral Care", "Body Wash", "Hand Wash", "Sanitizer"]}]}', 'ALL', false, 'hygiene,soap,toothbrush,sanitizer'),
(14, 'Health Devices', 'Thermometers, nebulizers, pulse oximeters', '🩺', true, 14, '{"fields": [{"name": "deviceType", "label": "Device Needed", "type": "select", "options": ["Thermometer", "Nebulizer", "Oximeter", "Massager"]}]}', 'ALL', false, 'devices,oximeter,thermometer,nebulizer'),
(15, 'Fitness and Nutrition', 'Protein powders, mass gainers, weight loss pills', '💪', true, 15, '{"fields": [{"name": "goal", "label": "Fitness Goal", "type": "select", "options": ["Muscle Gain", "Weight Loss", "General Health"]}]}', 'ALL', false, 'fitness,protein,nutrition,supplement'),
(16, 'Prescription Medicines', 'Critical drugs requiring verified prescriptions', '💊', true, 16, '{"fields": [{"name": "doctorName", "label": "Prescribing Doctor", "type": "text", "required": true}, {"name": "prescriptionDate", "label": "Prescription Date", "type": "date", "required": true}]}', 'ALL', true, 'prescription,antibiotic,chronic'),
(17, 'OTC Medicines', 'Pain relievers, cold pills, antacids', '🤒', true, 17, '{"fields": [{"name": "symptom", "label": "Primary Symptom", "type": "select", "options": ["Fever", "Headache", "Cough/Cold", "Acidity", "Body Pain"]}]}', 'ALL', false, 'otc,paracetamol,cough,cold,acidity'),
(18, 'Surgical Equipment', 'Surgical gloves, bandages, syringes', '✂️', true, 18, '{"fields": [{"name": "isInstitution", "label": "Buying for an Institution?", "type": "boolean"}]}', 'ALL', false, 'surgical,syringe,gloves,bandages'),
(19, 'Sexual Wellness', 'Condoms, lubricants, wellness supplements', '🤫', true, 19, '{"fields": [{"name": "productType", "label": "Product Type", "type": "select", "options": ["Contraceptives", "Lubricants", "Supplements"]}]}', 'ALL', false, 'wellness,contraceptive,lubricant,condoms'),
(20, 'Mother and Child Care', 'Pregnancy supplements, stretch mark creams, maternity kits', '🍼', true, 20, '{"fields": [{"name": "pregnancyTrimester", "label": "Pregnancy Trimester (if applicable)", "type": "select", "options": ["1st Trimester", "2nd Trimester", "3rd Trimester", "Postpartum", "N/A"]}]}', 'WOMEN', false, 'mother,pregnancy,maternity,stretch-mark');

-- Products
MERGE INTO products (id, name, description, mrp, selling_price, discount_percent, manufacturer, salt_composition, uses, side_effects, directions, image_url, prescription_required, featured, active, stock, rating, review_count, pack_size, dosage_form, category_id, created_at, updated_at)
KEY (id) VALUES
(1, 'Dolo 650mg Tablet', 'Paracetamol tablet for fever and pain relief. One of the most trusted brands in India.', 30.00, 25.50, 15.0, 'Micro Labs Ltd', 'Paracetamol 650mg', 'Fever, Headache, Body ache, Toothache, Pain relief', 'Nausea, Allergic reaction (rare), Liver damage (overdose)', 'Take 1-2 tablets every 4-6 hours as needed. Do not exceed 4 tablets in 24 hours.', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400', false, true, true, 500, 4.5, 1250, 'Strip of 15 tablets', 'Tablet', 17, NOW(), NOW()),
(2, 'Crocin Advance 500mg', 'Fast-acting paracetamol for quick relief from pain and fever.', 25.00, 21.25, 15.0, 'GSK Pharma', 'Paracetamol 500mg', 'Fever, Headache, Cold, Flu symptoms, Mild pain', 'Nausea, Skin rash (rare)', 'Take 1-2 tablets with water. Maximum 4 tablets per day.', 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400', false, true, true, 400, 4.3, 890, 'Strip of 15 tablets', 'Tablet', 17, NOW(), NOW()),
(3, 'Azithral 500mg', 'Azithromycin antibiotic for bacterial infections. Requires prescription.', 120.00, 95.00, 20.8, 'Alembic Pharmaceuticals', 'Azithromycin 500mg', 'Bacterial infections, Respiratory tract infections, Skin infections', 'Diarrhea, Nausea, Abdominal pain, Vomiting', 'Take as directed by physician. Complete the full course.', 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400', true, false, true, 200, 4.2, 560, 'Strip of 3 tablets', 'Tablet', 16, NOW(), NOW()),
(4, 'Himalaya Liv.52 DS', 'Liver care supplement. Protects the liver against various hepatotoxins.', 230.00, 195.50, 15.0, 'Himalaya Wellness', 'Caper Bush, Chicory, Black Nightshade, Arjuna, Yarrow, Tamarisk', 'Liver protection, Appetite improvement, Digestion', 'Generally well-tolerated', 'Take 1-2 tablets twice daily or as directed.', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400', false, true, true, 350, 4.6, 2100, 'Bottle of 60 tablets', 'Tablet', 12, NOW(), NOW()),
(5, 'Volini Spray 100ml', 'Quick pain relief spray for muscle pain, sprains, and joint pain.', 225.00, 191.25, 15.0, 'Sun Pharma', 'Diclofenac Diethylamine, Methyl Salicylate, Menthol, Linseed Oil', 'Muscle pain, Joint pain, Sprains, Back pain', 'Skin irritation, Redness at application site', 'Spray on affected area 3-4 times daily. For external use only.', 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400', false, true, true, 280, 4.1, 750, '100ml Spray', 'Spray', 10, NOW(), NOW()),
(6, 'Ensure Diabetes Care 400g', 'Nutritional supplement specially designed for people with diabetes.', 750.00, 637.50, 15.0, 'Abbott', 'Protein, Fiber, Vitamins, Minerals, Slowly Digestible Carbs', 'Nutritional support, Blood sugar management, Energy', 'Bloating, Gas (initial use)', 'Mix 6 scoops in 200ml water. Take 1-2 servings daily.', 'https://images.unsplash.com/photo-1505576399279-0d309cb92cf6?w=400', false, true, true, 150, 4.4, 980, '400g Powder', 'Powder', 8, NOW(), NOW()),
(7, 'Neutrogena Sunscreen SPF 50', 'Ultra Sheer Dry-Touch sunscreen. Lightweight, non-greasy formula.', 599.00, 479.20, 20.0, 'Johnson and Johnson', 'Avobenzone, Homosalate, Octisalate, Octocrylene', 'Sun protection, UV damage prevention, Skin care', 'Mild skin irritation (sensitive skin)', 'Apply generously 15 minutes before sun exposure. Reapply every 2 hours.', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400', false, true, true, 220, 4.3, 1560, '50ml Tube', 'Lotion', 6, NOW(), NOW()),
(8, 'Accu-Chek Active Glucometer', 'Blood glucose monitoring system with test strips for diabetes management.', 1299.00, 999.00, 23.1, 'Roche', 'Electronic Glucometer Device', 'Blood sugar monitoring, Diabetes management', 'Minor finger prick discomfort', 'Follow device instructions for blood glucose testing.', 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400', false, true, true, 80, 4.5, 430, '1 Glucometer + 10 Strips', 'Device', 14, NOW(), NOW()),
(9, 'Centrum Multivitamin', 'Complete A to Zinc multivitamin for overall nutritional support.', 450.00, 382.50, 15.0, 'Pfizer', 'Vitamin A, B, C, D, E, K, Iron, Zinc, Calcium', 'Nutritional supplement, Immunity support, Energy boost', 'Nausea (if taken on empty stomach)', 'Take 1 tablet daily with food.', 'https://images.unsplash.com/photo-1559757175-7cb057fba93c?w=400', false, true, true, 300, 4.4, 1200, 'Bottle of 30 tablets', 'Tablet', 11, NOW(), NOW()),
(10, 'Pampers Baby Diapers (L)', 'Ultra-soft baby diapers with up to 12 hours of dryness protection.', 899.00, 719.20, 20.0, 'P and G', 'Absorbent polymer, Cotton-like material', 'Baby diapering, Leakage protection', 'Skin irritation (rare, if allergic)', 'Change diaper every 3-4 hours or as needed.', 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400', false, false, true, 180, 4.6, 2300, 'Pack of 64 diapers (Large)', 'Diaper', 1, NOW(), NOW()),
(11, 'Vicks VapoRub 50ml', 'Topical cough suppressant for relief from cough, cold, and body ache.', 145.00, 130.50, 10.0, 'P and G Health', 'Camphor, Menthol, Eucalyptus Oil', 'Cough relief, Nasal congestion, Body ache, Cold symptoms', 'Skin irritation (sensitive skin)', 'Apply on chest, throat and back. For external use only.', 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400', false, false, true, 400, 4.5, 3200, '50ml Jar', 'Ointment', 17, NOW(), NOW()),
(12, 'ORS Electral Powder', 'Oral rehydration salts for dehydration due to diarrhea or vomiting.', 22.00, 19.80, 10.0, 'FDC Ltd', 'Sodium Chloride, Potassium Chloride, Sodium Citrate, Dextrose', 'Dehydration, Diarrhea, Vomiting, Electrolyte imbalance', 'Nausea (if consumed too quickly)', 'Dissolve 1 sachet in 1 litre of drinking water. Sip frequently.', 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400', false, false, true, 600, 4.3, 890, 'Pack of 4 sachets', 'Powder', 17, NOW(), NOW()),
(13, 'Dabur Chyawanprash 500g', 'Ayurvedic immunity booster with Amla and 40+ Ayurvedic herbs.', 270.00, 229.50, 15.0, 'Dabur India', 'Amla, Ashwagandha, Giloy, Pippali, 40+ herbs', 'Immunity boost, Stamina, Digestion, Respiratory health', 'Generally well-tolerated', 'Take 1-2 teaspoons twice daily with milk.', 'https://images.unsplash.com/photo-1505576399279-0d309cb92cf6?w=400', false, true, true, 250, 4.5, 4500, '500g Jar', 'Paste', 12, NOW(), NOW()),
(14, 'Cipla i-Pill Emergency', 'Emergency contraceptive pill. To be taken within 72 hours.', 120.00, 108.00, 10.0, 'Cipla', 'Levonorgestrel 1.5mg', 'Emergency contraception', 'Nausea, Vomiting, Fatigue, Headache, Irregular bleeding', 'Take 1 tablet orally within 72 hours of unprotected intercourse.', 'https://images.unsplash.com/photo-1559757175-7cb057fba93c?w=400', false, false, true, 150, 3.9, 340, '1 Tablet', 'Tablet', 19, NOW(), NOW()),
(15, 'Re-Lyte Eye Drops', 'Lubricant eye drops for dry, irritated eyes and computer vision syndrome.', 85.00, 72.25, 15.0, 'Cipla', 'Carboxymethylcellulose 0.5%', 'Dry eyes, Eye irritation, Computer eye strain', 'Temporary blurred vision, Eye burning (rare)', 'Instill 1-2 drops in affected eye(s) as needed.', 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400', false, false, true, 320, 4.2, 670, '10ml Bottle', 'Eye Drops', 17, NOW(), NOW()),
(16, 'Omez 20mg Capsule', 'Acidity, GERD, and gastric ulcers.', 95.00, 76.00, 20.0, 'Dr. Reddys', 'Omeprazole 20mg', 'Acidity, GERD, Stomach ulcers, Heartburn', 'Headache, Diarrhea, Nausea, Abdominal pain', 'Take 1 capsule before breakfast.', 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400', false, false, true, 380, 4.4, 1100, 'Strip of 15 capsules', 'Capsule', 17, NOW(), NOW()),
(17, 'Premium Foldable Wheelchair', 'Heavy-duty steel foldable wheelchair with comfortable padded seats and armrests.', 8500.00, 6800.00, 20.0, 'Kosmochem', 'High-grade Steel, Rexine Seat', 'Mobility support, Patient transport, Rehabilitation', 'None', 'Unfold the wheelchair, lock the wheels, assist user to sit, unlock and move.', 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400', false, true, true, 45, 4.7, 180, '1 Unit', 'Device', 10, NOW(), NOW()),
(18, 'Adult Diapers Premium (L)', 'Leakproof adult diapers with wetness indicator and high absorption capacity for seniors.', 650.00, 520.00, 20.0, 'Friends', 'Super Absorbent Polymer, Soft Pulp', 'Incontinence management, Elderly care, Bedridden care', 'Rashes (change regularly)', 'Wear like regular undergarments, change when wetness indicator changes color.', 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400', false, true, true, 120, 4.8, 320, 'Pack of 10 diapers', 'Diaper', 3, NOW(), NOW()),
(19, 'Adjustable Quad Walking Cane', 'Four-legged stable walking cane with adjustable height settings for balance assistance.', 1200.00, 960.00, 20.0, 'Rehab Care', 'Anodized Aluminum, Rubber tips', 'Walking assistance, Stability, Post-op recovery', 'None', 'Adjust height to waist level, grip the handle, walk keeping the cane on the opposite side of weak leg.', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400', false, true, true, 75, 4.5, 95, '1 Cane', 'Device', 3, NOW(), NOW());

-- Seed Discounts
MERGE INTO discounts (id, code, description, discount_type, discount_value, min_order_amount, max_discount_amount, usage_limit, used_count, valid_from, valid_until, active, created_at)
KEY (id) VALUES
(1, 'WELCOME10', 'Get 10% off on your first order', 'PERCENTAGE', 10.00, 100.00, 50.00, 1000, 24, '2026-01-01', '2027-12-31', true, NOW()),
(2, 'HEALTH20', 'Save 20% on vitamins and wellness', 'PERCENTAGE', 20.00, 200.00, 100.00, 500, 12, '2026-01-01', '2027-12-31', true, NOW()),
(3, 'FLAT50', 'Flat 50 off on orders above 499', 'FLAT', 50.00, 499.00, 50.00, 100, 5, '2026-01-01', '2027-12-31', true, NOW());

-- Seed Inventory
MERGE INTO inventory (id, product_id, quantity, reorder_level, batch_number, manufacturing_date, expiry_date, supplier, supplier_contact, last_restocked, created_at, updated_at)
KEY (id) VALUES
(1, 1, 500, 15, 'BATCH-DOL650A', '2026-02-15', '2026-06-15', 'Micro Labs Supplier', '+91 9876543210', NOW(), NOW(), NOW()),
(2, 2, 400, 10, 'BATCH-CRO500B', '2026-01-10', '2027-01-10', 'GSK Logistics', '+91 9876543211', NOW(), NOW(), NOW()),
(3, 4, 350, 12, 'BATCH-LIV52C', '2026-03-01', '2026-05-30', 'Himalaya Distributors', '+91 9876543212', NOW(), NOW(), NOW()),
(4, 8, 8, 10, 'BATCH-ACCU8D', '2025-12-15', '2028-12-15', 'Roche Med Devices', '+91 9876543213', NOW(), NOW(), NOW()),
(5, 9, 300, 20, 'BATCH-CENT9E', '2026-02-20', '2027-02-20', 'Pfizer India', '+91 9876543214', NOW(), NOW(), NOW()),
(6, 17, 45, 5, 'BATCH-WHL17A', '2026-01-01', '2030-01-01', 'Kosmochem Devices', '+91 9999988888', NOW(), NOW(), NOW()),
(7, 18, 120, 10, 'BATCH-DPR18B', '2026-03-01', '2028-03-01', 'Friends Corp', '+91 9999988888', NOW(), NOW(), NOW()),
(8, 19, 75, 5, 'BATCH-CAN19C', '2026-02-15', '2029-02-15', 'Rehab Care Supplier', '+91 9999988888', NOW(), NOW(), NOW());
